### ISSUE TITLE
share your nginx img

### ISSUE THREAD

**Issue by emperorente** [kaija/k8s-scale-webhook#1]
HI,
can you share your nginx image & k8s svc.yaml?i just can't get the metris from my own nginx image in k8s

**Comment by kaija** [comment]
docker pull kaija/nginx_status
https://github.com/kaija/docker-nginx-status
You can find the docker image in above github link.
The kubernetes manifest is and old one, please use deployment instead of replica controller.

**Comment by emperorente** [comment]
Got it , thank you
